gen_rule (
  name = 'all',
  deps = [
    ':reloadable',
    ':base',
  ]
)

cc_binary(
  name = 'reloadable',
  srcs = [
    'reloadable.cc',
  ],
)

cc_binary(
  name = 'base',
  srcs = [
    'base.cc',
  ],
)
